run btn bug corrected
Cereal84/AnadiCSV pull request #15
Opened 2024-09-25 11:04 UTC by 0xkafkaa

#13 Corrected the bug for run btn issue

Regard,
0xkafkaa.

2024-09-26 08:35 UTC, Cereal84 commented on anadi/layouts/horizontal_layout.tcss
> +	margin-top: 1;
This param has not correct identation

2024-09-26 08:36 UTC, Cereal84 requested changes

2024-09-26 08:36 UTC, Cereal84 commented on anadi/layouts/horizontal_layout.tcss
> +	margin-top: 1;
This param has not correct identation.

2024-09-26 09:13 UTC, 0xkafkaa commented on anadi/layouts/horizontal_layout.tcss
> +	margin-top: 1;
Its corrected now.

2024-10-01 08:19 UTC, Cereal84 approved these changes

2024-10-01 08:19 UTC, merged

2024-10-01 08:19 UTC, Cereal84 commented
Thank you @0xkafkaa