New file
Cereal84/AnadiCSV pull request #39
Opened 2024-10-03 12:53 UTC by Brijeshthummar02

issue #3

2024-10-03 14:17 UTC, Cereal84 requested changes

2024-10-03 14:17 UTC, Cereal84 commented on install.sh
> +}
The function _check_requirements_ must be moved in _scripts/utils.sh_ file.

2024-10-03 14:25 UTC, Cereal84 commented
In anadi.sh are used some commands like $(pwd), those commands are supported in Windows ?
Did you try it on windows machine ?

2024-10-07 12:42 UTC, Cereal84 commented
Hi @Brijeshthummar02 any news?
Do you need some help?

2024-10-07 15:02 UTC, Brijeshthummar02 commented
@Cereal84 to be honest i'm not sure if  those commands are supported in Windows ?

2024-10-07 16:03 UTC, Cereal84 commented
> @Cereal84 to be honest i'm not sure if  those commands are supported in Windows ?

Those things are part of the "Windows Support", otherwise the risk is to have not the support for Windows.

I don't know if those commands are supported (or not) by Windows, unfortunately ilI have no Windows machine.

2024-10-08 12:37 UTC, Cereal84 commented
@Brijeshthummar02 the support must be added in both install and run script, otherwise even if the installation goes well the user cannot use it anyway.

I haven't Windows installed so I cannot test it. I expect that who is adding the support in some O.S. does the test too in order to see if everything works.

2024-11-23 11:46 UTC, Cereal84 commented
Close this Pull Request because the user seems not more interested in resolving it.

2024-11-23 11:46 UTC, closed without merging